### ISSUE TITLE
Pip not working anymore :(

### ISSUE THREAD

**Issue by cyborgdennett** [mcfletch/pyvrml97#1]
pip install PyVRML97 PyVRML97_accelerate
Collecting PyVRML97
  Downloading PyVRML97-2.3.1.tar.gz (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 KB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting PyVRML97_accelerate
  Downloading PyVRML97-accelerate-2.3.0b1.zip (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.3/112.3 KB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\caspe\AppData\Local\Temp\pip-install-w4h3zg31\pyvrml97-accelerate_d3d836d0e36b4e22a70408ef406741ff\setup.py", line 6
          except ImportError, err:
                            ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Stephanowicz** [comment]
Sorry, but this is just the **least** error, which can easily be solved with
`except ImportError as err:`

the true fun then follows xD

just an excerpt

```
src\fieldaccel2.c(3552): error C2039: "exc_value" ist kein Member von "_ts".
D:\Progs\Coding\Python313\include\cpython/pystate.h(59): note: Siehe Deklaration von "_ts"
src\fieldaccel2.c(3553): error C2039: "exc_traceback" ist kein Member von "_ts".
D:\Progs\Coding\Python313\include\cpython/pystate.h(59): note: Siehe Deklaration von "_ts"
src\fieldaccel2.c(3554): error C2039: "exc_type" ist kein Member von "_ts".
D:\Progs\Coding\Python313\include\cpython/pystate.h(59): note: Siehe Deklaration von "_ts"
src\fieldaccel2.c(3555): error C2039: "exc_value" ist kein Member von "_ts".
D:\Progs\Coding\Python313\include\cpython/pystate.h(59): note: Siehe Deklaration von "_ts"
src\fieldaccel2.c(3556): error C2039: "exc_traceback" ist kein Member von "_ts".
D:\Progs\Coding\Python313\include\cpython/pystate.h(59): note: Siehe Deklaration von "_ts"
src\fieldaccel2.c(4331): warning C4047: "Funktion": Anzahl der Dereferenzierungen bei "PyObject *" und "int" unterschiedlich
src\fieldaccel2.c(4331): warning C4024: "PyCode_New": unterschiedliche Typen für formalen und übergebenen Parameter 14
src\fieldaccel2.c(4331): warning C4047: "Funktion": Anzahl der Dereferenzierungen bei "int" und "PyObject *" unterschiedlich
src\fieldaccel2.c(4331): warning C4024: "PyCode_New": unterschiedliche Typen für formalen und übergebenen Parameter 15
src\fieldaccel2.c(4331): error C2198: "PyCodeObject *PyCode_New(int,int,int,int,int,PyObject *,PyObject *,PyObject *,PyObject *,PyObject *,PyObject *,PyObject *,PyObject *,PyObject *,int,PyObject *,PyObject *)": Nicht genügend Argumente für Aufruf.
src\fieldaccel2.c(4331): warning C4996: 'PyCode_New': deprecated in 3.12
src\fieldaccel2.c(4377): error C2037: Auf der linken Seite von "f_lineno" wird eine undefinierte struct/union "_frame" bestimmt
```
